### ISSUE TITLE
Question about Table.5 and some pre-trained proposals

### ISSUE THREAD

**Issue by qsunyuan** [LutingWang/OADP#10]
非常启发的工作。但个人有一些疑惑的地方。

1. 关于表5的消融实验，能详细介绍一下3,4,5的crop region具体是怎么样的吗?
2. 关于实验配置部分，https://github.com/LutingWang/OADP#proposals 这部分是用来pkl文件offline proposals的吗?或者我遗漏了哪些细节。

**Comment by qsunyuan** [comment]
soco_star_mask_rcnn_r50_fpn_400e.pth 这个文件和detpro的 https://github.com/dyabel/detpro#prepare-data 有什么区别吗？
在detpro中的readme如下
All models use the backbone pretrained with [SoCo](https://github.com/hologerry/SoCo) which can be downloaded from [google drive](https://drive.google.com/file/d/1z6Tb2MPFJDv9qpEyn_J0cJcXOguKTiL0/view?usp=sharing) [baiduyun (code:kwps)](https://pan.baidu.com/s/1FHN-9vsH16w4TAusyHnXvg). Put the pretrained backbone under data/.

**Comment by LutingWang** [comment]
1. The following figure illustrates the different crop strategies

**Comment by LutingWang** [comment]
1. The following figure illustrates the differences between the crop strategies

<img width="612" alt="image" src="https://github.com/LutingWang/OADP/assets/39944944/5308e6e5-53b7-40fb-9aee-1240e223042a">

2. the proposals are obtained offline through RPN or OLN. Both are trained solely using base annotations. Subsequently, these extracted proposals are utilized by the OAKE module to extract features for distillation.

**Comment by LutingWang** [comment]
The two checkpoint files are identical. We renamed the checkpoint file to ease the identification of the original SOCO checkpoint.

**Comment by qsunyuan** [comment]
谢谢作者细致的回复！
