### ISSUE TITLE
About the instance segmentation task

### ISSUE THREAD

**Issue by ShenghaiRong** [LutingWang/OADP#11]
Thanks for your excellent work and for sharing the code. Even though it is not the main task in this paper, this paper also reports the performance of the instance segmentation task. I am interested in the OV-IS too, could you provide the config and corresponding code of OADP for training and evaluation on the OV-IS task? 
Look forward to your reply, thank you!

**Comment by LutingWang** [comment]
We have updated the README and provided commands to evaluate the instance segmentation performance of OV-LVIS OADP. Just so you know, the accuracy reported in our paper was obtained using a model with large-scale jitter augmentation, so there is a gap compared to the checkpoints currently provided.
