### ISSUE TITLE
如何跑自己的数据集？

### ISSUE THREAD

**Issue by LinSY546749** [LutingWang/OADP#16]
作者你好，我想为我自己coco格式的数据集划分基类和新类，并且将coco dataset和oadp.base.globals_里的类别改成了我自己数据集的类别，但是运行build_annotations.py的时候报错，请问我该如何修改?
<img width="512" alt="1705675831523" src="https://github.com/LutingWang/OADP/assets/71642276/50d3f161-730c-452c-a46c-ccbe510d8869">

**Comment by LutingWang** [comment]
从报错信息来看，应该是犹豫自定义数据的 annotation 使用了未定义的 category id。具体来说，`build_annotations.py` 在处理 `instances_val2017.json` 时，会遍历所有 annotations，其中一个 annotation 的 `category_id` 字段的值是 5。但是这个 `category_id` 并没有出现在 `instances_val2017.json` 的 categories 字段中，所以导致报错。可以检查自定义的数据文件是否完整

P.S. 赶 paper + 春节所以回复不及时，不好意思 😢
