### ISSUE TITLE
阿里网盘中为什么没有文件？

### ISSUE THREAD

**Issue by Originlightwkp** [LutingWang/OADP#4]

**Comment by LutingWang** [comment]
阿里云盘不支持分享二进制文件，我们正在把数据迁移到百度网盘和谷歌云盘上

**Comment by ZJUJeffLai** [comment]
It seems I can only find globals.tar.gz and blocks.tar.gz in the shared folder but cannot find objects.tar.gz.
Also, I found I cannot tar them. Could you help check if the right files are uploaded to the shared folder?

**Comment by LutingWang** [comment]
> It seems I can only find globals.tar.gz and blocks.tar.gz in the shared folder but cannot find objects.tar.gz. Also, I found I cannot tar them. Could you help check if the right files are uploaded to the shared folder?

We have double-checked that both `globals.tar.gz` and `blocks.tar.gz` can be decompressed via `tar -zxvf ${FILENAME}`. For your reference, the MD5 checksum for `globals.tar.gz` is `6c9c9a7517c667e8320fb2e55292cd3a`, and for `blocks.tar.gz` is `cd5cfb5e0dd9279d73d32ea6cf491e12`.

The object features (>100GB) are much larger than the `globals.tar.gz` and `blocks.tar.gz`. Therefore, we recommend regenerating these features by yourself, which may be faster. We are trying to upload the features, but may take some time to finish.

**Comment by LutingWang** [comment]
> Thanks! After we generate object features, do we still need to run these?
> 
> > cd objects/train2017
> > ls > objects
> > split -d -3000 - objects. < objects
> > for i in objects.[0-9][0-9]; do
> > zip -q -9 "$i.zip" -@ < "$i"
> > mv "$i.zip" ../..
> > done
> > rm objects*

You are welcome. No, the commands are used for compressing the object features, before uploading to Baidu Netdisk. If you are generating object features, you can completely ignore these commands. Otherwise, if you will be using our pre-computed features, the commands may provide useful information on how to decompress the tar files.

**Comment by DaqiLin** [comment]
OADP/data
├── coco
│   └── proposals
│       ├── rpn_r101_fpn_coco_train.pkl
│       ├── rpn_r101_fpn_coco_val.pkl
│       ├── oln_r50_fpn_coco_train.pkl
│       └── oln_r50_fpn_coco_val.pkl
└── lvis_v1
    └── proposals
        ├── oln_r50_fpn_lvis_train.pkl
        └── oln_r50_fpn_lvis_val.pkl
I can't find "oln_r50_fpn_lvis_train.pkl" in the Baidu Netdisk

**Comment by LutingWang** [comment]
> OADP/data ├── coco │ └── proposals │ ├── rpn_r101_fpn_coco_train.pkl │ ├── rpn_r101_fpn_coco_val.pkl │ ├── oln_r50_fpn_coco_train.pkl │ └── oln_r50_fpn_coco_val.pkl └── lvis_v1 └── proposals ├── oln_r50_fpn_lvis_train.pkl └── oln_r50_fpn_lvis_val.pkl I can't find "oln_r50_fpn_lvis_train.pkl" in the Baidu Netdisk

Uploaded. But lvis support is still under testing. We will release the config and checkpoint for lvis training soon.
