### ISSUE TITLE
Please I run‘python -m oadp.build_annotations’.But appear AttributeError: module 'todd' has no attribute 'StoreMeta'.Why is that, hope to get answered, thank you.

### ISSUE THREAD

**Issue by 123456hxh** [LutingWang/OADP#5]
Please I run‘python -m oadp.build_annotations’.But appear AttributeError: module 'todd' has no attribute 'StoreMeta'.Why is that, hope to get answered, thank you.

**Comment by LutingWang** [comment]
Please use the following command to check if the `todd` version is 0.3.0

```bash
python -c "from importlib.metadata import version; print(version('todd_ai'))"
```

If the version is 0.3.0, it would be helpful if the full traceback is provided.

**Comment by 123456hxh** [comment]
Thank you for your  
But it will appear ERROR: No matching distribution found for todd_ai==0.3.0

**Comment by 123456hxh** [comment]
Thank you for reply. @LutingWang
But it will appear ERROR: No matching distribution found for todd_ai==0.3.0

**Comment by LutingWang** [comment]
This seems like a pip error. If you are using custom pip sources, the following command might help

```shell
pip install todd_ai==0.3.0 -i https://pypi.org/simple/
```

If the problem persists, you can try to install from the whl file, which you can download manually from `https://pypi.org/project/todd-ai/#files`.

**Comment by 123456hxh** [comment]
Thank you
